# Configuration for HPV Snakemake pipeline.


# 1) This is where the remapped bam files can be found.
glob_path: /path/to/*.bam

# 2) This is name of the deliverable directory.
deliver_proj: HPV_type_cohort_projectID_date

# 3) Update the parser function in the Snakefile to match the bam filenames.

# 4) Update the wrapper.sh script.

# 5) Choose a read depth of 4 or 6 by selecting the correct TVC json file
#    below.

# -------------------------------------------------------------
# These files will not change between runs
# -------------------------------------------------------------

# Reference files
hg_fasta: /path/to/HPV16Ref_hg19.fasta
len_bed: /path/to/hpv16.bed
amp_bed: /path/to/HPV16_amplicon_no_primer_01172015.bed

# Tools and packages
# Warning - you MUST use GATK version 3.3!
gatk: /path/to/GenomeAnalysisTK-3.3-0/GenomeAnalysisTK.jar

vc_bin: /path/to/tvc-5.0.3/bin
vc_pipe: /path/to/tvc-5.0.3/bin/variant_caller_pipeline.py

# choose a TVC read depth of 4 or 6
#vc_param: /path/to/germline_low_stringency_no_het.json
vc_param: /path/to/germline_low_stringency_no_het_low_depth.json

cov_dev: /path/to/cgrCoverageDev

snpeff: /path/to/snpEff
# the bed file has a custom list of features (usually regulation)
snpeff_bed:  /path/to/snpEff/data/hpv16/source/regulation.bed
hpv_type: hpv16

# You need glu installed in your PATH
